const data = {
  portfolioList: [
    {
      id: 1,
      title: 'E-commerce Web',
      groupFilter: 'filter-web',
      src: '/assets/img/portfolio/e-commerce/homepage-min.png',
      display: '/assets/img/portfolio/e-commerce/homepage.png',
      category: 'E-commerce Web',
      projectURL: 'https://billie-ecommerce-app.herokuapp.com/',
      urlName: 'https://billie-ecommerce-app.herokuapp.com/',
      sourceCode: 'https://github.com/billiea96/ecommerce-app',
      technologies: 'MongooDB, Express JS, React JS, Node JS, & Redux',
      detail:
        'This was a project that i built as a result of my learning of MERN Stack development. In this project there is a homepage containing products for sale along with their ratings and prices. Besides that there are another features or pages which are cart, shopping cart view, place order, order payment, authentication and authorization, admin pages, etc. I am using Paypal for payment integration and I am also using JSON Web Tokens (JWTs) for authentication. I built this project using MERN Stack and Redux for state management in React.',
      imgs: [
        '/assets/img/portfolio/e-commerce/Homepage.png',
        '/assets/img/portfolio/e-commerce/Product-Page-min.png',
        '/assets/img/portfolio/e-commerce/Shopping-Cart-Page.png',
        '/assets/img/portfolio/e-commerce/Checkout-Order-Page.png',
        '/assets/img/portfolio/e-commerce/Payment-Page.png',
        '/assets/img/portfolio/e-commerce/Order-History-Page.png',
        '/assets/img/portfolio/e-commerce/Login.png',
        '/assets/img/portfolio/e-commerce/Admin-Page.png',
      ],
    },
    {
      id: 2,
      title: 'Childcare Information System',
      groupFilter: 'filter-web',
      src: '/assets/img/portfolio/childcare/Profile-Anak-min.png',
      display: '/assets/img/portfolio/childcare/Profile-Anak.png',
      category: 'System Information Web',
      projectURL: '#',
      urlName: '-',
      sourceCode: 'https://github.com/billiea96/Childcare',
      technologies: 'Codeigniter, MySQL, & JQuery',
      detail:
        "This project is about information system for a childcare. The system handles all the activity that occur in the childcare like children's diary that note all their activities each day, what is their temperature, what do they eat, how do they sleep, how do they defecate and what does it looks like, are they sick, what medicenes and vitamins are given, etc. Besides that, there are monthly report about kids health and their development both sensory and motor. And also there are still another features like registration, monthly payment, catering, master data, etc. I built this website using Codeigniter and Mysql as the database.",
      imgs: [
        '/assets/img/portfolio/childcare/Profile-Anak.png',
        '/assets/img/portfolio/childcare/Anak.png',
        '/assets/img/portfolio/childcare/Catatan-Harian.png',
        '/assets/img/portfolio/childcare/Catatan-Makan.png',
        '/assets/img/portfolio/childcare/catatan-pengeluaran 1.png',
        '/assets/img/portfolio/childcare/daftar-katering 1.png',
        '/assets/img/portfolio/childcare/Laporan-Harian.png',
        '/assets/img/portfolio/childcare/Laporang-Kesehatan.png',
        '/assets/img/portfolio/childcare/Perkembangan.png',
        '/assets/img/portfolio/childcare/Login.JPG',
        '/assets/img/portfolio/childcare/Pendaftaran.png',
        '/assets/img/portfolio/childcare/Master.png',
        '/assets/img/portfolio/childcare/Pembayaran.png',
      ],
    },
    {
      id: 3,
      title: 'A Store Information System',
      groupFilter: 'filter-web',
      src: '/assets/img/portfolio/tokocahaya/Nota-Beli-min.png',
      display: '/assets/img/portfolio/tokocahaya/Nota-Beli.png',
      category: 'System Information Web',
      projectURL: '#',
      urlName: '-',
      sourceCode: 'https://bitbucket.org/cintiawan/tokocahaya/src/web/',
      technologies: 'Codeigniter, MySQL, & JQuery',
      detail:
        'I built this project with a friend as team when we did practical work in college. This project is about system information for a store especially for store that sale tableware, kitchen utensils, and houseware store. The system handles all store transaction like sales order, sales, purchases order, purchases, sales returns, purchases returns, account receivable payments, debt payments, goods stocks, master data, etc, and also theirs reporting system. I built the system using Codeigniter and MySQL as database.',
      imgs: [
        '/assets/img/portfolio/tokocahaya/Nota-Beli.png',
        '/assets/img/portfolio/tokocahaya/Laporan-Pelunasan Piutang.png',
        '/assets/img/portfolio/tokocahaya/Laporan-Pembelian.png',
        '/assets/img/portfolio/tokocahaya/Laporan-Penjualan.png',
        '/assets/img/portfolio/tokocahaya/Laporan-Stok Barang.png',
        '/assets/img/portfolio/tokocahaya/Master-Barang.png',
        '/assets/img/portfolio/tokocahaya/Nota-Jual.png',
        '/assets/img/portfolio/tokocahaya/Retur-Beli.png',
        '/assets/img/portfolio/tokocahaya/Retur-Jual.png',
      ],
    },
    {
      id: 4,
      title: 'A Store Accounting Information System',
      groupFilter: 'filter-web',
      src: '/assets/img/portfolio/psia/Penjualan-min.png',
      display: '/assets/img/portfolio/psia/Penjualan.png',
      category: 'Accounting System Information Web',
      projectURL: '#',
      urlName: '-',
      sourceCode: 'https://github.com/billiea96/sia_toko',
      technologies: 'Codeigniter, MySQL, & JQuery',
      detail:
        'This project is about accounting system information for a store. The system handles store transaction like sales, purchases, account receivable payments, debt payments, balance report, cash flow statement, journal report, income statement and ending balance report. I built the system using Codeigniter and MySQL as database.',
      imgs: [
        '/assets/img/portfolio/psia/Penjualan.png',
        '/assets/img/portfolio/psia/Pembelian.png',
        '/assets/img/portfolio/psia/Pelunasan Jual.png',
        '/assets/img/portfolio/psia/Pelunasan Beli.png',
        '/assets/img/portfolio/psia/Laporan-Arus-Kas.png',
        '/assets/img/portfolio/psia/Laporan-Buku-Besar.png',
        '/assets/img/portfolio/psia/Laporan-Buku-Besar 2.png',
        '/assets/img/portfolio/psia/Laporan-Jurnal.png',
        '/assets/img/portfolio/psia/Laporan-Laba Rugi.png',
        '/assets/img/portfolio/psia/Laporan-Neraca.png',
        '/assets/img/portfolio/psia/Laporan-Saldo Akhir.png',
      ],
    },
  ],
};

export default data;
